[platformio]
src_dir = .

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -w

board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB

lib_deps =
    bblanchon/ArduinoJson@^7.4.3
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit NeoPixel@^1.12.0
    milesburton/DallasTemperature@^3.9.0
    claws/BH1750@^1.1.0
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
